const ActionTypes = {
  MYVCARD_DATA_REQUESTED: 'MYVCARD_DATA_REQUESTED',
  MYVCARD_DATA_FETCHED: 'MYVCARD_DATA_FETCHED',
  MYVCARD_DATA_REJECTED: 'MYVCARD_DATA_REJECTED',
  GITHUB_DATA_REQUESTED: 'GITHUB_DATA_REQUESTED',
  GITHUB_DATA_FETCHED: 'GITHUB_DATA_FETCHED',
  GITHUB_DATA_REJECTED: 'GITHUB_DATA_REJECTED',
};

export default ActionTypes;
